#' Title
#'
#' @param z A numeric vector with observations of the threshold/control variable
#' @param d The delay parameter
#' @param r A vector of length 2 containing the trhesholds
#' @param phi A vector containing the autoregressive coefficients of regime 0.
#' Note that a constant/intercept must be specified. If you don't want a
#' constant, you can just set it to zero.
#' @param psi A vector containing the autoregressive coefficients of regime 0
#' @param resvar A vector containing the residual variances of regime 0 and 1
#' @param init_vals Initial values: The first length(z)-max(p0, p1, d) values
#' are fixed in the model.
#' @param start_regime A starting regime, 0 or 1
#'
#' @return Simulated time series generated by the BAR model
#' @export
#'
#' @examples
barsim <- function(z, d, r, phi, psi, resvar = c(1, 1),
                   init_vals = NULL,
                   start_regime = NULL) {
  a <- n_ineff(get_order(psi), get_order(phi), d)

  if (missing(init_vals)){
    init_vals <- rep(0, times = a)
  }
  init_R <- rep(9L, times = a)

  check_sim_input(z, d, r, phi, psi, resvar, init_vals, start_regime)

  p0    <- get_order(phi)
  p1    <- get_order(psi)
  z_del <- z[time_del(y = z, d = d, p0, p1, d_sel = d)]
  H     <- ts_hys(z_del, r0 = r[1], r1 = r[2])
  R     <- c(init_R, ts_reg(H, start = start_regime))
  eff   <- time_eff(z, d, p0, p1)
  y     <- c(init_vals, eff)

  y <- simulate(y, eff, R, phi, psi, resvar)

  return(y)
}



