#' Title
#'
#' @param z A numeric vector with observations of the threshold/control variable
#' @param d The delay parameter
#' @param r A vector of length 2 containing the trhesholds
#' @param phi A vector containing the autoregressive coefficients of regime 0.
#' Note that a constant/intercept must be specified. If you don't want a
#' constant, you can just set it to zero.
#' @param psi A vector containing the autoregressive coefficients of regime 0
#' @param resvar A vector containing the residual variances of regime 0 and 1
#' @param init_vals Initial values: The first length(z)-max(p0, p1, d) values
#' are fixed in the model.
#' @param start_regime A starting regime, 0 or 1
#'
#' @return Simulated time series generated by the BAR model
#' @export
#'
#' @examples
barsim <- function(r, d, phi_R0, phi_R1, resvar,
                   init_vals    = NULL,
                   z            = NULL,
                   length       = NULL,
                   n_switches   = NULL,
                   start_regime = NULL) {

  if (is.null(z)) {
    check_zsim_input(r, length, n_switches, start_regime)
    z <- simulate_z(r, length, n_switches, start_regime)
  }

  check_sim_input(z, d, r, phi, psi, resvar, init_vals, start_regime)
  p0 <- get_order(phi)
  p1 <- get_order(psi)
  a  <- n_ineff(p0, p1, d)

  if (is.null(init_vals)){
    coe <- if (start_regime == 0) phi else psi
    init_vals <- get_init_vals(coe, resvar[start_regime + 1], a)
  }
  init_R <- rep(start_regime, times = a)

  z_del <- z[time_del(y = z, d = d, p0, p1, d_sel = d)]
  H     <- ts_hys(z_del, r0 = r[1], r1 = r[2])
  R     <- c(init_R, ts_reg(H, start = start_regime))
  eff   <- time_eff(z, d, p0, p1)
  y_    <- c(init_vals, eff) # Placeholder, just to have the correct length
  y     <- simulate_y(y_, eff, R, phi, psi, resvar)
  true  <- name_true_vals(d, r, phi, psi, resvar)

  data  <- new_bardata(y = y,
                       z = z,
                       H = c(rep(NA, a), H == -1),
                       R = R,
                       r = r,
                       n_ineff = a)

  return(list(data = data, true_vals = true))
}


name_true_vals <- function(d, r, phi, psi, resvar) {
  names(d)   <- "delay"
  names(r)   <- c("r0", "r1")
  names(phi) <- paste0("phi", 0:(length(phi)-1))
  names(psi) <- paste0("psi", 0:(length(psi)-1))
  names(resvar) <- paste0("regime", 0:1)
  return(list(d = d, r = r, phi = phi, psi = psi, resvar = resvar))
}



